# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Comifer < Formula
  desc "git helper for generating commit log with emoji"
  homepage "https://jiko21.me/comifer/"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/jiko21/comifer/releases/download/v0.1.0/comifer_0.1.0_macOS_x86_64.tar.gz"
      sha256 "36566ed385d461502e4d3e1b155d29528a4378010a7e3a787a14c26fb066f7fd"

      def install
        bin.install "comifer"
      end
    end
    on_arm do
      url "https://github.com/jiko21/comifer/releases/download/v0.1.0/comifer_0.1.0_macOS_arm64.tar.gz"
      sha256 "6eaedb19fed7f0c8194d4943e3b486f7f33a8177eac8e537be25ea84bf5bdab6"

      def install
        bin.install "comifer"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jiko21/comifer/releases/download/v0.1.0/comifer_0.1.0_Linux_x86_64.tar.gz"
        sha256 "8f39d06f9698e4af4ef1068f47db3378a443077c96fda118181431953bf9827b"

        def install
          bin.install "comifer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jiko21/comifer/releases/download/v0.1.0/comifer_0.1.0_Linux_arm64.tar.gz"
        sha256 "a6e781a4839da85f8fea7f66c5f51293b601156f92bb183debb97acce4070e22"

        def install
          bin.install "comifer"
        end
      end
    end
  end
end
