# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Comifer < Formula
  desc "git helper for generating commit log with emoji"
  homepage "https://jiko21.me/comifer/"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jiko21/comifer/releases/download/v0.0.1/comifer_darwin_x86_64.tar.gz"
      sha256 "0f2be9250db1d4a444fc5eb54c9ff268ba8fe8a85db6357b17ffdaab86e5741c"

      def install
        bin.install "comifer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jiko21/comifer/releases/download/v0.0.1/comifer_darwin_arm64.tar.gz"
      sha256 "d82c0900b98037e44fb87998ddba9faa400adf366a14112d15d987b868c04a8d"

      def install
        bin.install "comifer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jiko21/comifer/releases/download/v0.0.1/comifer_linux_x86_64.tar.gz"
      sha256 "00cf69bbfddcc1c8cf7f7bdeb25e9c43dcf24bf8bd7e4f7f37759286f5040af8"

      def install
        bin.install "comifer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jiko21/comifer/releases/download/v0.0.1/comifer_linux_arm64.tar.gz"
      sha256 "0c1742a7498abb5da69eb8159987ffcc0fcc58d0d07003194354e28abc892e47"

      def install
        bin.install "comifer"
      end
    end
  end
end
